Remove UI, Girder, and devops from this repository (#833)
* Remove UI, Girder, and devops from this repository.

Those components have moved to HistomicsUI or digital_slide_archive.

The ctk_cli adjustments are now taken from the girder-slicer-cli-web package.

Switch to using tox instead of the Girder 2/CMake test harness.

Moved from unittest to pytest for some of the tests.

Fix several warnings from the Bugbear warning set, mainly about using mutable default variables in function definitions.

* Disable tests that need to be converted.

These tests should all be converted to run with pytest and use local resources or data files pulled from a standardized source rather than development servers.

* Fix testing for Python < 3.6.

* Fix how the dask requirement is specified.

Dask now requires the [dataframe] extra requires to be specified or it fails when we try to use certain functions.

* Update unit testing instructions

Co-authored-by: Mohamed Amgad Tageldin <mtageld@emory.edu>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,33 +1,142 @@
-version: 2
+version: 2.1
+commands:
+  tox:
+    description: "Run tox"
+    parameters:
+      env:
+        type: string
+    steps:
+      - run:
+          name: Upgrade pip
+          command: pip install -U pip
+      - run:
+          name: Upgrade virtualenv and tox
+          command: pip install -U virtualenv tox
+      - run:
+          name: Install scikit-build
+          command: pip install scikit-build
+      - run:
+          name: Run tests via tox
+          # Piping through cat does less buffering of the output but can
+          # consume the exit code
+          command: tox -e << parameters.env >> | cat; test ${PIPESTATUS[0]} -eq 0
+  coverage:
+    description: "Upload coverage"
+    steps:
+      - run:
+          name: Install Codecov client
+          command: pip install codecov
+      - run:
+          name: Upload coverage
+          # Retry as codecov can be flaky
+          command: for i in $(seq 1 10); do [ $i -gt 1 ] && echo "retrying $i" && sleep 5; codecov --required --disable search pycov gcov --root project --file .tox/coverage/py_coverage.xml && s=0 && break || s=$?; done; (exit $s)
+
 jobs:
-  build:
+  # Because some of our tests use docker-compose as part of the test, we can't
+  # use a CircleCI docker environment, since those environments run sub dockers
+  # in a separate environment.  The 201808-01 machine environment has versions
+  # of Python 2.7, 3.5, 3.6, 3.7 with specific subversions.
+  py27:
+    working_directory: ~/project
+    machine:
+      image: circleci/classic:201808-01
+    steps:
+      - checkout
+      - run:
+          name: Use pyenv to set python version
+          command: |
+            pyenv versions
+            pyenv global 2.7.12
+      - tox:
+          env: py27
+      - coverage
+  py35:
+    working_directory: ~/project
+    machine:
+      image: circleci/classic:201808-01
+    steps:
+      - checkout
+      - run:
+          name: Use pyenv to set python version
+          command: |
+            pyenv versions
+            pyenv global 3.5.2
+      - tox:
+          env: py35
+      - coverage
+  py36:
+    working_directory: ~/project
+    machine:
+      image: circleci/classic:201808-01
+    steps:
+      - checkout
+      - run:
+          name: Use pyenv to set python version
+          command: |
+            pyenv versions
+            pyenv global 3.6.5
+      - tox:
+          env: py36
+      - coverage
+  py37:
+    working_directory: ~/project
+    machine:
+      image: circleci/classic:201808-01
+    steps:
+      - checkout
+      - run:
+          name: Use pyenv to set python version
+          command: |
+            pyenv versions
+            pyenv global 3.7.0
+      - tox:
+          env: py37
+      - coverage
+  lint_and_docs:
+    working_directory: ~/project
+    docker:
+      - image: circleci/python:3.7
+    steps:
+      - checkout
+      - run:
+          name: install pandoc
+          command: sudo apt-get install -y pandoc pandoc-citeproc
+      - tox:
+          env: docs,flake8
+  docker:
+    working_directory: ~/project
+    machine: true
+    steps:
+      - checkout
+      - run:
+          name: Build HistomicsTK docker
+          command: docker build --force-rm -t dsarchive/histomicstk .
+  wheels:
     working_directory: ~/project
     docker:
       - image: circleci/python:3.6
-      - image: docker:17.05.0-ce-git
+      - image: docker:git
     steps:
       - checkout
       - setup_remote_docker
+      - run:
+          name: Setup virtual environment
+          command: |
+            if [ ! -d env ]; then python -m virtualenv env || python -m venv env; fi
+            echo ". $CIRCLE_WORKING_DIRECTORY/env/bin/activate" >> $BASH_ENV
+      - run:
+          name: Install python packages
+          command: pip install setuptools_scm twine
       - run:
           name: Build wheels
           command: ./build_wheels.sh
       - store_artifacts:
           path: wheels
-      # - run:
-      #     name: Run tests via tox
-      #     command: tox | cat
-      # - run:
-      #     name: Install Codecov client
-      #     command: pip install codecov
-      # - run:
-      #     name: Upload coverage
-      #     command: codecov --disable search pycov gcov --root project --file build/test/coverage/py_coverage.xml build/test/coverage/cobertura-coverage.xml
-
   release:
     working_directory: ~/project
     docker:
       - image: circleci/python:3.6
-      - image: docker:17.05.0-ce-git
+      - image: docker:git
     steps:
       - checkout
       - setup_remote_docker
@@ -50,13 +159,64 @@ workflows:
   version: 2
   ci:
     jobs:
-      - build:
+      - py27:
           filters:
             tags:
               only: /^v.*/
+            branches:
+              ignore:
+                - gh-pages
+      - py35:
+          filters:
+            tags:
+              only: /^v.*/
+            branches:
+              ignore:
+                - gh-pages
+      - py36:
+          filters:
+            tags:
+              only: /^v.*/
+            branches:
+              ignore:
+                - gh-pages
+      - py37:
+          filters:
+            tags:
+              only: /^v.*/
+            branches:
+              ignore:
+                - gh-pages
+      - lint_and_docs:
+          filters:
+            tags:
+              only: /^v.*/
+            branches:
+              ignore:
+                - gh-pages
+      - docker:
+          filters:
+            tags:
+              only: /^v.*/
+            branches:
+              ignore:
+                - gh-pages
+      - wheels:
+          filters:
+            tags:
+              only: /^v.*/
+            branches:
+              ignore:
+                - gh-pages
       - release:
           requires:
-            - build
+            - py27
+            - py35
+            - py36
+            - py37
+            - lint_and_docs
+            - wheels
+            - docker
           filters:
             tags:
               only: /^v.*/
diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,160 +1,30 @@
+sudo: false
+dist: xenial
 language: python
 python:
   - "2.7"
   - "3.5"
   - "3.6"
-
-cache:
-  directories:
-    - $HOME/.cache
-
-sudo: required
-
-dist: trusty
-
-services:
-  - docker
-  - rabbitmq
-
-compiler:
-  - gcc
-
+  - "3.7"
 addons:
   apt:
     packages:
-      # Pillow dependencies (see
-      # https://pillow.readthedocs.org/en/latest/installation.html)
-      - libtiff5-dev
-      - libjpeg8-dev
-      - zlib1g-dev
-      - libfreetype6-dev
-      - liblcms2-dev
-      - libwebp-dev
-      - tcl8.6-dev
-      - tk8.6-dev
-      - python-tk
-      # vips
-      - libvips-tools
-      # openjpeg
-      - libglib2.0-dev
-      - libjpeg-dev
-      - libxml2-dev
-      - libpng12-dev
-      # openslide
-      - autoconf
-      - automake
-      - libtool
-      - pkg-config
-      - libcairo2-dev
-      - libgdk-pixbuf2.0-dev
-      - libxml2-dev
-      - libsqlite3-dev
-      # girder worker
-      # - rabbitmq-server
-      # pandoc for displaying jupyter notebook examples on ReadTheDocs
       - pandoc
       - pandoc-citeproc
-      # canvas
-      - libgif-dev
-
-before_install:
-    # Fix a travis/boto issue.  See
-    # https://github.com/travis-ci/travis-ci/issues/7940
-  - sudo rm -f /etc/boto.cfg
-
-  - pip install -U pip
-
-  - mkdir -p $HOME/.cache/node_modules || true
-  - ln -sf $HOME/.cache/node_modules .
-  - nvm install v8
-  - npm install -g npm@6.10.3
-  - npm install -g npm-install-retry
-  - npm --version
-  - npm prune
-
-  - CACHE="$HOME/.cache" OPENJPEG_VERSION=2.1.2 OPENJPEG_FILE=v2.1.2.tar.gz OPENJPEG_DIR=openjpeg-2.1.2 LIBTIFF_VERSION=4.0.8 OPENSLIDE_VERSION=3.4.1 source .install-openslide.sh
-
-  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export PY3="true"; else export PY2="true"; fi
-  - GIRDER_VERSION=2.x-maintenance
-  - GIRDER_WORKER_VERSION=v0.5.1
-  - LARGE_IMAGE_VERSION=2.x-maintenance
-  - SLICER_CLI_WEB_VERSION=2.x-maintenance
-  - main_path=$PWD
-  - build_path=$HOME/build
-  - mkdir -p $build_path
-
-  - girder_path=$HOME/girder
-  - rm -fr $girder_path
-  - git clone https://github.com/girder/girder.git $girder_path && git -C $girder_path checkout $GIRDER_VERSION
-  - ln -sf $main_path $girder_path/plugins/
-  - ls -l $girder_path/plugins
-
-  - girder_worker_path=$HOME/girder_worker
-  - git clone https://github.com/girder/girder_worker.git $girder_worker_path && git -C $girder_worker_path checkout $GIRDER_WORKER_VERSION
-  - cp $PWD/plugin_tests/data/girder_worker.cfg $girder_worker_path/girder_worker/worker.local.cfg
-  - if [ -n "${PY3}" ]; then
-      sudo pip2 install --no-cache-dir -U setuptools &&
-      sudo pip2 install --no-cache-dir -U $girder_worker_path'[girder_io,docker]' ;
-      else
-      pip install --no-cache-dir -U $girder_worker_path'[girder_io,docker]' ;
-      fi
-
-  - large_image_path=$girder_path/plugins/large_image
-  - git clone https://github.com/girder/large_image.git $large_image_path && git -C $large_image_path checkout $LARGE_IMAGE_VERSION
-
-  - slicer_cli_web_path=$girder_path/plugins/slicer_cli_web
-  - git clone https://github.com/girder/slicer_cli_web.git $slicer_cli_web_path && git -C $slicer_cli_web_path checkout $SLICER_CLI_WEB_VERSION
-
-  - export MONGO_VERSION=3.4.19
-  - export PY_COVG="ON"
-  - CACHE=$HOME/.cache source $girder_path/scripts/install_mongo.sh
-  - mkdir /tmp/db
-  - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
-  - mongod --version
-
-  - CACHE=$HOME/.cache CMAKE_VERSION=3.8.0 CMAKE_SHORT_VERSION=3.8 source $girder_path/scripts/install_cmake.sh
-  - cmake --version
-
 install:
-  - cd $girder_path
-  - pip install -U --upgrade-strategy eager -r requirements-dev.txt
-  - pip install -U -e .[worker]
-  - cd $large_image_path
-  - pip install --no-cache-dir 'numpy>=1.12.1'
-  - pip install --upgrade --no-cache-dir --force-reinstall --ignore-installed openslide-python Pillow
-
-  - pip install -U .[memcached,openslide]
-  - python setup.py install
-  - cd $main_path
-  - pip install -r requirements_dev.txt
-    # needs to be installed in dev mode for it to place binaries of cython/c extensions in place
-  - pip install -e .
-  - cd $girder_path
-  - pip install -U -r $slicer_cli_web_path/requirements.txt
-    # Fix versions that were upgraded that shouldn't have been
-  - pip install botocore 'python-dateutil<2.7'
-  - npm-install-retry
-  - BABEL_ENV=cover NYC_CWD="$main_path" girder-install web --plugins=jobs,worker,large_image,slicer_cli_web,HistomicsTK --dev
-  - npm list || true
-  - pip install jupyter sphinx sphinx_rtd_theme nbsphinx travis-sphinx
-  - pip freeze  # report what we have installed
-
+  - pip install --upgrade pip
+  - pip install --upgrade virtualenv
+  - if [ ${TRAVIS_PYTHON_VERSION:0:3} == "2.7" ]; then pip install virtualenv==20.0.5; fi
+  - pip install tox-travis
+  - pip install scikit-build
+  # If the last tag is more than 50 commits away, we need to fetch more for
+  # the scm_version module to determine the version.
+  - git fetch --depth=1000
 script:
-  - cd $girder_worker_path
-  - python2 -m girder_worker >/tmp/worker.out 2>&1 &
-  - cd $build_path
-  - cmake -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_EXECUTABLE:FILEPATH="`which python`" -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} -DRUN_CORE_TESTS:BOOL="OFF" -DTEST_PLUGINS:STRING="HistomicsTK" $girder_path
-  - make -j 5
-  - JASMINE_TIMEOUT=15000 ctest -VV -j 3
-  - cd $main_path
-  - if [ ${TRAVIS_PYTHON_VERSION:0:3} == "3.6" ]; then travis-sphinx build --source=$main_path/docs; fi
-
-after_failure:
-  # On failures, show the worker output and other information
-  - pip freeze
-  - cat /tmp/worker.out
-
+  # Piping through cat does less buffering of the output but can consume the
+  # exit code
+  - tox | cat; test ${PIPESTATUS[0]} -eq 0
 after_success:
-  - bash <(curl -s https://codecov.io/bash) -R $main_path -s $girder_path
-  - cd $main_path
-  - if [ ${TRAVIS_PYTHON_VERSION:0:3} == "3.6" ]; then travis-sphinx deploy; fi
+  - pip install codecov
+  - codecov --disable search pycov gcov --file build/test/coverage/py_coverage.xml
+  # - if [ ${TRAVIS_PYTHON_VERSION:0:3} == "3.7" ]; then pip install travis-sphinx; travis-sphinx -o docs/build -v deploy -b sphinx,master; fi
